version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: laptop_store_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laptop_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: